import { db } from "./firebase";
import { collection, doc, writeBatch } from "firebase/firestore";
import { Product } from "./types";

export const SEED_PRODUCTS: Omit<Product, "id">[] = [
  // --- BASES (BASE_CONTAINER) - 10 Itens ---
  {
    name: "Caixa MDF Decorada P",
    price: 12.5,
    type: "BASE_CONTAINER",
    category: "Caixas",
    unit: "un",
    description_adjective: "Delicada",
    imageUrl: "https://placehold.co/400x400/png?text=MDF+P",
    inStock: true,
    capacity: 4,
  },
  {
    name: "Caixa MDF Decorada M",
    price: 18.9,
    type: "BASE_CONTAINER",
    category: "Caixas",
    unit: "un",
    description_adjective: "Versátil",
    imageUrl: "https://placehold.co/400x400/png?text=MDF+M",
    inStock: true,
    capacity: 8,
  },
  {
    name: "Caixa MDF Decorada G",
    price: 24.9,
    type: "BASE_CONTAINER",
    category: "Caixas",
    unit: "un",
    description_adjective: "Espaçosa",
    imageUrl: "https://placehold.co/400x400/png?text=MDF+G",
    inStock: true,
    capacity: 12,
  },
  {
    name: "Cesta de Vime Redonda P",
    price: 15.0,
    type: "BASE_CONTAINER",
    category: "Cestas",
    unit: "un",
    description_adjective: "Clássica",
    imageUrl: "https://placehold.co/400x400/png?text=Vime+P",
    inStock: true,
    capacity: 5,
  },
  {
    name: "Cesta de Vime Oval M",
    price: 25.9,
    type: "BASE_CONTAINER",
    category: "Cestas",
    unit: "un",
    description_adjective: "Rústica",
    imageUrl: "https://placehold.co/400x400/png?text=Vime+M",
    inStock: true,
    capacity: 10,
  },
  {
    name: "Cesta de Vime Alça G",
    price: 35.0,
    type: "BASE_CONTAINER",
    category: "Cestas",
    unit: "un",
    description_adjective: "Imponente",
    imageUrl: "https://placehold.co/400x400/png?text=Vime+G",
    inStock: true,
    capacity: 15,
  },
  {
    name: "Cesta Coração Madeira",
    price: 22.0,
    type: "BASE_CONTAINER",
    category: "Cestas",
    unit: "un",
    description_adjective: "Romântica",
    imageUrl: "https://placehold.co/400x400/png?text=Coracao",
    inStock: true,
    capacity: 7,
  },
  {
    name: "Caixa Kraft Visor P",
    price: 5.5,
    type: "BASE_CONTAINER",
    category: "Caixas",
    unit: "un",
    description_adjective: "Moderna",
    imageUrl: "https://placehold.co/400x400/png?text=Kraft+P",
    inStock: true,
    capacity: 3,
  },
  {
    name: "Caixa Kraft Visor M",
    price: 8.5,
    type: "BASE_CONTAINER",
    category: "Caixas",
    unit: "un",
    description_adjective: "Elegante",
    imageUrl: "https://placehold.co/400x400/png?text=Kraft+M",
    inStock: true,
    capacity: 6,
  },
  {
    name: "Bandeja Café da Manhã",
    price: 45.0,
    type: "BASE_CONTAINER",
    category: "Madeira",
    unit: "un",
    description_adjective: "Sofisticada",
    imageUrl: "https://placehold.co/400x400/png?text=Bandeja",
    inStock: true,
    capacity: 12,
  },

  // --- PRODUTOS PADRÃO (STANDARD_ITEM) - 12 Itens ---
  {
    name: "Sabonete TodoDia (Unidade)",
    price: 6.5,
    type: "STANDARD_ITEM",
    category: "Corpo e Banho",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Sabonete",
    inStock: true,
    itemSize: 1,
  },
  {
    name: "Esmalte Una",
    price: 25.9,
    type: "STANDARD_ITEM",
    category: "Maquiagem",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Esmalte",
    inStock: true,
    itemSize: 1,
  },
  {
    name: "Batom Faces Matte",
    price: 19.9,
    type: "STANDARD_ITEM",
    category: "Maquiagem",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Batom",
    inStock: true,
    itemSize: 1,
  },
  {
    name: "Desodorante Roll-on Erva Doce",
    price: 22.9,
    type: "STANDARD_ITEM",
    category: "Corpo e Banho",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Rollon",
    inStock: true,
    itemSize: 1,
  },
  {
    name: "Hidratante Mãos Maracujá",
    price: 42.9,
    type: "STANDARD_ITEM",
    category: "Corpo e Banho",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Maos",
    inStock: true,
    itemSize: 2,
  },
  {
    name: "Caixa Sabonetes (5un)",
    price: 32.9,
    type: "STANDARD_ITEM",
    category: "Corpo e Banho",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Cx+Sabonete",
    inStock: true,
    itemSize: 2,
  },
  {
    name: "Body Splash TodoDia",
    price: 69.9,
    type: "STANDARD_ITEM",
    category: "Perfumaria",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Splash",
    inStock: true,
    itemSize: 2,
  },
  {
    name: "Óleo Séve Amêndoas",
    price: 89.9,
    type: "STANDARD_ITEM",
    category: "Corpo e Banho",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Seve",
    inStock: true,
    itemSize: 2,
  },
  {
    name: "Hidratante Corporal 400ml",
    price: 65.9,
    originalPrice: 89.9,
    type: "STANDARD_ITEM",
    category: "Corpo e Banho",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Hidratante+400",
    inStock: true,
    featured: true,
    itemSize: 3,
  },
  {
    name: "Colônia Kayak Clássico",
    price: 145.9,
    type: "STANDARD_ITEM",
    category: "Perfumaria",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Kayak",
    inStock: true,
    itemSize: 3,
  },
  {
    name: "Kit Barba Homem",
    price: 95.0,
    type: "STANDARD_ITEM",
    category: "Barba",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Kit+Barba",
    inStock: true,
    itemSize: 3,
  },
  {
    name: "Perfume Essencial Oud",
    price: 220.0,
    type: "STANDARD_ITEM",
    category: "Perfumaria",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Essencial",
    inStock: true,
    itemSize: 3,
  },

  // --- FUNDOS (FILLER) - 8 Itens ---
  {
    name: "Palha de Madeira Natural",
    price: 3.0,
    type: "FILLER",
    category: "Naturais",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Palha+Nat",
    inStock: true,
  },
  {
    name: "Palha de Madeira Clara",
    price: 3.5,
    type: "FILLER",
    category: "Naturais",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Palha+Clara",
    inStock: true,
  },
  {
    name: "Papel de Seda Vermelho",
    price: 1.0,
    type: "FILLER",
    category: "Papéis",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Seda+Verm",
    inStock: true,
  },
  {
    name: "Papel de Seda Branco",
    price: 1.0,
    type: "FILLER",
    category: "Papéis",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Seda+Bran",
    inStock: true,
  },
  {
    name: "Papel de Seda Azul",
    price: 1.0,
    type: "FILLER",
    category: "Papéis",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Seda+Azul",
    inStock: true,
  },
  {
    name: "Papel de Seda Rosa",
    price: 1.0,
    type: "FILLER",
    category: "Papéis",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Seda+Rosa",
    inStock: true,
  },
  {
    name: "Papel Picado Colorido",
    price: 2.5,
    type: "FILLER",
    category: "Papéis",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Picado",
    inStock: true,
  },
  {
    name: "Tecido Tule Branco",
    price: 4.0,
    type: "FILLER",
    category: "Tecidos",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Tule",
    inStock: true,
  },

  // --- FITAS (RIBBON) - 10 Itens ---
  {
    name: "Fita Cetim 10mm Vermelha",
    price: 1.0,
    type: "RIBBON",
    category: "Fitas Cetim",
    unit: "m",
    imageUrl: "https://placehold.co/400x400/png?text=Cetim+Verm",
    inStock: true,
  },
  {
    name: "Fita Cetim 10mm Dourada",
    price: 1.2,
    type: "RIBBON",
    category: "Fitas Cetim",
    unit: "m",
    imageUrl: "https://placehold.co/400x400/png?text=Cetim+Ouro",
    inStock: true,
  },
  {
    name: "Fita Cetim 22mm Rosa",
    price: 1.5,
    type: "RIBBON",
    category: "Fitas Cetim",
    unit: "m",
    imageUrl: "https://placehold.co/400x400/png?text=Cetim+Rosa",
    inStock: true,
  },
  {
    name: "Fita Cetim 22mm Azul Marinho",
    price: 1.5,
    type: "RIBBON",
    category: "Fitas Cetim",
    unit: "m",
    imageUrl: "https://placehold.co/400x400/png?text=Cetim+Azul",
    inStock: true,
  },
  {
    name: "Fita Gorgurão 15mm Estampada",
    price: 2.5,
    type: "RIBBON",
    category: "Gorgurão",
    unit: "m",
    imageUrl: "https://placehold.co/400x400/png?text=Gorgurao",
    inStock: true,
  },
  {
    name: "Laço Pronto P Vermelho",
    price: 1.0,
    type: "RIBBON",
    category: "Laços Prontos",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Laco+P",
    inStock: true,
  },
  {
    name: "Laço Pronto M Dourado",
    price: 1.5,
    type: "RIBBON",
    category: "Laços Prontos",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Laco+M",
    inStock: true,
  },
  {
    name: "Laço Bola Grande",
    price: 3.5,
    type: "RIBBON",
    category: "Laços Prontos",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Laco+Bola",
    inStock: true,
  },
  {
    name: "Fio de Juta Natural",
    price: 0.5,
    type: "RIBBON",
    category: "Rústico",
    unit: "m",
    imageUrl: "https://placehold.co/400x400/png?text=Juta",
    inStock: true,
  },
  {
    name: "Fita Organza Branca",
    price: 2.0,
    type: "RIBBON",
    category: "Fitas Especiais",
    unit: "m",
    imageUrl: "https://placehold.co/400x400/png?text=Organza",
    inStock: true,
  },

  // --- EMBALAGENS (WRAPPER) - 8 Itens ---
  {
    name: "Saco Transparente 15x20",
    price: 0.5,
    type: "WRAPPER",
    category: "Sacos",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Saco+15x20",
    inStock: true,
  },
  {
    name: "Saco Transparente 20x30",
    price: 0.8,
    type: "WRAPPER",
    category: "Sacos",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Saco+20x30",
    inStock: true,
  },
  {
    name: "Saco Transparente 30x45",
    price: 1.2,
    type: "WRAPPER",
    category: "Sacos",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Saco+30x45",
    inStock: true,
  },
  {
    name: "Saco Estampado Coração",
    price: 1.0,
    type: "WRAPPER",
    category: "Sacos Decorados",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Saco+Coracao",
    inStock: true,
  },
  {
    name: "Saco Estampado Estrelas",
    price: 1.0,
    type: "WRAPPER",
    category: "Sacos Decorados",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Saco+Estrela",
    inStock: true,
  },
  {
    name: "Celofane Transparente (Folha)",
    price: 1.5,
    type: "WRAPPER",
    category: "Folhas",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Celofane",
    inStock: true,
  },
  {
    name: "Celofane Decorado Natal",
    price: 2.0,
    type: "WRAPPER",
    category: "Folhas",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Celo+Natal",
    inStock: true,
  },
  {
    name: "Saco Metalizado Prata",
    price: 1.5,
    type: "WRAPPER",
    category: "Sacos Especiais",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Saco+Prata",
    inStock: true,
  },

  // --- ATACADO (SUPPLY_BULK) - 6 Itens ---
  {
    name: "Pct 50 Sacos 15x20",
    price: 18.0,
    type: "SUPPLY_BULK",
    category: "Atacado Embalagens",
    unit: "pct",
    imageUrl: "https://placehold.co/400x400/png?text=50+Sacos",
    inStock: true,
  },
  {
    name: "Pct 50 Sacos 20x30",
    price: 25.0,
    type: "SUPPLY_BULK",
    category: "Atacado Embalagens",
    unit: "pct",
    imageUrl: "https://placehold.co/400x400/png?text=50+Sacos+M",
    inStock: true,
  },
  {
    name: "Pct 100 Laços Prontos P",
    price: 35.0,
    type: "SUPPLY_BULK",
    category: "Atacado Laços",
    unit: "pct",
    imageUrl: "https://placehold.co/400x400/png?text=100+Lacos",
    inStock: true,
  },
  {
    name: "Rolo Fita Cetim 50m",
    price: 12.0,
    type: "SUPPLY_BULK",
    category: "Atacado Fitas",
    unit: "un",
    imageUrl: "https://placehold.co/400x400/png?text=Rolo+Fita",
    inStock: true,
  },
  {
    name: "Fardo Palha 1kg",
    price: 28.0,
    type: "SUPPLY_BULK",
    category: "Atacado Fundos",
    unit: "kg",
    imageUrl: "https://placehold.co/400x400/png?text=Palha+1kg",
    inStock: true,
  },
  {
    name: "Pct 10 Caixas Kraft Desmontadas",
    price: 40.0,
    type: "SUPPLY_BULK",
    category: "Atacado Caixas",
    unit: "pct",
    imageUrl: "https://placehold.co/400x400/png?text=10+Caixas",
    inStock: true,
  },
];

export const runSeed = async () => {
  const batch = writeBatch(db);
  const productsRef = collection(db, "products");
  SEED_PRODUCTS.forEach((prod) => {
    const newDocRef = doc(productsRef);
    batch.set(newDocRef, { ...prod, id: newDocRef.id });
  });
  await batch.commit();
  console.log("Banco de dados atualizado com 50+ produtos!");
};
